--- 
services:
  shopizer-db: 
    environment:
      - MYSQL_ROOT_PASSWORD=shopizer123
      - MYSQL_DATABASE=SALESMANAGER
      - MYSQL_USER=shopizer_db_user
      - MYSQL_PASSWORD=my-password
    image: mysql/mysql-server:5.7
    container_name: shopizer-db
    networks:
      - shopizer-network
    ports: 
      - "3307:3306"
    volumes: 
      - ./db:/var/lib/mysql
  shopizer: 
    depends_on: 
      - shopizer-db
    environment: 
      - "SPRING_PROFILES_ACTIVE=dependency"
      - "JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "elasticsearch.server.host=shopizer-es"
      - "elasticsearch.server.port=9200"
      - "db.jdbcUrl=jdbc:mysql://shopizer-db:3306/SALESMANAGER?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
      - "db.user=shopizer_db_user"
      - "db.password=my-password"
      - "elasticsearch.security.password=NOTREQUIRED"
      - "config.displayShipping=true"
      - "config.googleMapsKey=NO"
      - "config.recaptcha.secretKey=NO"
      - "config.recaptcha.siteKey=NO"
      - "config.shippingDistancePreProcessor.acceptedZones=QC,ON,NB,NY,CA,FL,NC,SC"
      - "config.shippingDistancePreProcessor.apiKey=NO"
    image: shopizerecomm/shopizer:latest
    container_name: shopizer
    mem_limit: 1024m
    networks:
      - shopizer-network
    links: 
      - shopizer-db
      - shopizer-es
    depends_on:
      - shopizer-db
      - shopizer-es
    ports: 
      - "8080:8080"
  shopizer-es: 
    environment: 
      - "cluster.name=shopizer"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: shopizer-es
    networks:
      - shopizer-network
    mem_limit: 1g
    ports: 
      - "9200:9200"
    ulimits: 
      memlock: 
        hard: -1
        soft: -1
    volumes:
      - ./es:/usr/share/elasticsearch/data
version: "2.2"

networks:
  shopizer-network: